services:
  dev-payment-api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: dev-payment-api

    working_dir: /opt/www

    command: php bin/hyperf.php start

    develop:
      watch:
        - action: restart
          path: ./app
        - action: restart
          path: ./config
        - action: restart
          path: ./bin

    tty: true
    stdin_open: true

    volumes:
      - ./:/opt/www

    ports:
      - "9501:9501"

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

    networks:
      - dev-payment-network

  mysql:
    image: mysql:8.4

    container_name: dev-payment-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - dev-payment-mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - dev-payment-network

  redis:
    image: redis:7-alpine

    container_name: dev-payment-redis

    restart: unless-stopped

    volumes:
      - dev-payment-redis-data:/data

    networks:
      - dev-payment-network

volumes:
  dev-payment-mysql-data:
  dev-payment-redis-data:

networks:
  dev-payment-network:
    driver: bridge
